---
- name: Install mariadb-server
  yum:
    name: mariadb-server
    state: installed

- name: Enable and start mariadb-server
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install MySQL-python
  yum:
    name: MySQL-python
    state: installed
  when: mariadb_root_password is defined

