---
# install mariadb server
- include: install.yml
  tags: [install]

# configure root account
- include: conf_root_access.yml
  tags: [root]

# secure mariadb installation
- include: secure.yml
  when: mariadb_secure_installation
  tags: [secure]

# create/remove databases
- include: database.yml
  tags: [database]

# create/remove users
- include: user_conf.yml
  tags: [user]

# open firewalld port
- include: firewalld.yml
  tags: [firewall]
