---
- name: Install firewalld
  yum:
    name: firewalld
    state: installed

- name: Enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open Mariadb Firewall Port
  firewalld:
    port: "3306/tcp"
    state: enabled
    immediate: True
    permanent: true 
