---
- name: Create databases
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{mariadb_db_create}}"
  when: mariadb_db_create

- name: Remove databases
  mysql_db:
    name: "{{ item }}"
    state: absent
  with_items: "{{mariadb_db_remove}}"
  when: mariadb_db_remove
